# Generated by Django 3.0.7 on 2020-08-16 13:37

import coinql.hash
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='coinql.Node')),
            ],
            bases=(coinql.hash.HashMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invisible', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='coinql.Node')),
            ],
            bases=(coinql.hash.HashMixin, models.Model),
        ),
    ]
