# Generated by Django 3.0.7 on 2020-08-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinql', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='data_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='nonce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='verification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='data_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
