# Generated by Django 3.0.7 on 2020-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinql', '0004_auto_20200816_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='nonce',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
