# Generated by Django 3.0.7 on 2020-08-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinql', '0005_auto_20200816_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nonce',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='verification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
