# Generated by Django 3.0.7 on 2020-08-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinql', '0006_auto_20200816_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
